// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiApplication.Data;

#nullable disable

namespace WebApiApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260215135707_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiApplication.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gaming laptop",
                            ImgUri = "https://img/1",
                            Name = "Laptop",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 2,
                            ImgUri = "https://img/2",
                            Name = "Mouse",
                            Price = 50m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mechanical keyboard",
                            ImgUri = "https://img/3",
                            Name = "Keyboard",
                            Price = 120m
                        },
                        new
                        {
                            Id = 4,
                            Description = "IPS, 1440p",
                            ImgUri = "https://img/4",
                            Name = "Monitor 27\"",
                            Price = 280m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ultrawide, 144Hz",
                            ImgUri = "https://img/5",
                            Name = "Monitor 34\" UW",
                            Price = 520m
                        },
                        new
                        {
                            Id = 6,
                            Description = "HDMI + USB-A + PD",
                            ImgUri = "https://img/6",
                            Name = "USB-C Hub",
                            Price = 45m
                        },
                        new
                        {
                            Id = 7,
                            Description = "1080p webcam",
                            ImgUri = "https://img/7",
                            Name = "Webcam",
                            Price = 80m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Closed-back headset",
                            ImgUri = "https://img/8",
                            Name = "Headset",
                            Price = 90m
                        },
                        new
                        {
                            Id = 9,
                            Description = "USB condenser mic",
                            ImgUri = "https://img/9",
                            Name = "Microphone",
                            Price = 110m
                        },
                        new
                        {
                            Id = 10,
                            Description = "2.0 desktop speakers",
                            ImgUri = "https://img/10",
                            Name = "Speakers",
                            Price = 65m
                        },
                        new
                        {
                            Id = 11,
                            Description = "USB 3.2 Gen2",
                            ImgUri = "https://img/11",
                            Name = "External SSD 1TB",
                            Price = 140m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Portable storage",
                            ImgUri = "https://img/12",
                            Name = "External HDD 2TB",
                            Price = 85m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Wi-Fi 6 router",
                            ImgUri = "https://img/13",
                            Name = "Wi-Fi Router",
                            Price = 150m
                        },
                        new
                        {
                            Id = 14,
                            Description = "8-port gigabit",
                            ImgUri = "https://img/14",
                            Name = "Ethernet Switch",
                            Price = 55m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Energy monitoring",
                            ImgUri = "https://img/15",
                            Name = "Smart Plug",
                            Price = 18m
                        },
                        new
                        {
                            Id = 16,
                            Description = "RGB + warm white",
                            ImgUri = "https://img/16",
                            Name = "Smart Bulb",
                            Price = 15m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Adjustable brightness",
                            ImgUri = "https://img/17",
                            Name = "Desk Lamp",
                            Price = 35m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Aluminum stand",
                            ImgUri = "https://img/18",
                            Name = "Laptop Stand",
                            Price = 30m
                        },
                        new
                        {
                            Id = 19,
                            ImgUri = "https://img/19",
                            Name = "Office Chair Mat",
                            Price = 25m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Under-desk tray",
                            ImgUri = "https://img/20",
                            Name = "Cable Organizer",
                            Price = 12m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Surge protection",
                            ImgUri = "https://img/21",
                            Name = "Power Strip",
                            Price = 22m
                        },
                        new
                        {
                            Id = 22,
                            Description = "Backup power",
                            ImgUri = "https://img/22",
                            Name = "UPS 650VA",
                            Price = 110m
                        },
                        new
                        {
                            Id = 23,
                            Description = "High speed HDMI",
                            ImgUri = "https://img/23",
                            Name = "HDMI Cable 2m",
                            Price = 10m
                        },
                        new
                        {
                            Id = 24,
                            Description = "100W PD cable",
                            ImgUri = "https://img/24",
                            Name = "USB-C Cable 1m",
                            Price = 9m
                        },
                        new
                        {
                            Id = 25,
                            Description = "Extended desk mat",
                            ImgUri = "https://img/25",
                            Name = "Mouse Pad XL",
                            Price = 14m
                        },
                        new
                        {
                            Id = 26,
                            Description = "10,000mAh",
                            ImgUri = "https://img/26",
                            Name = "Portable Charger",
                            Price = 40m
                        },
                        new
                        {
                            Id = 27,
                            Description = "USB Bluetooth 5.0",
                            ImgUri = "https://img/27",
                            Name = "Bluetooth Adapter",
                            Price = 13m
                        },
                        new
                        {
                            Id = 28,
                            ImgUri = "https://img/28",
                            Name = "USB Flash 128GB",
                            Price = 16m
                        },
                        new
                        {
                            Id = 29,
                            Description = "Mono laser printer",
                            ImgUri = "https://img/29",
                            Name = "Printer",
                            Price = 130m
                        },
                        new
                        {
                            Id = 30,
                            Description = "Document scanner",
                            ImgUri = "https://img/30",
                            Name = "Scanner",
                            Price = 95m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
